apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: apache/airflow:2.3.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: airflow-data
          mountPath: /usr/local/airflow/data
      - name: dbt
        image: dbt-labs/dbt:latest
        volumeMounts:
        - name: airflow-data
          mountPath: /usr/local/airflow/data
      volumes:
      - name: airflow-data
        persistentVolumeClaim:
          claimName: airflow-data-pvc
